version: "3.9"
services:
  api-tokens:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    command: ["java", "-DSPRING_PROFILES_ACTIVE=not_local", "-jar", "app.jar"]